// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGZbmz8igxEn3tr2OkCcRgMlqMuXvW6E0',
    appId: '1:1034229118044:web:6feb0db4c8f86e67ce2299',
    messagingSenderId: '1034229118044',
    projectId: 'lunchsphere',
    authDomain: 'lunchsphere.firebaseapp.com',
    storageBucket: 'lunchsphere.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCucvex36F12zY-pizIFa-ONlomBoeL6Vc',
    appId: '1:1034229118044:android:58902f122ca3f773ce2299',
    messagingSenderId: '1034229118044',
    projectId: 'lunchsphere',
    storageBucket: 'lunchsphere.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJBzr_CM05sCOxZ4MswhKbL3NBmfVWuSU',
    appId: '1:1034229118044:ios:7f76e371b0ad1964ce2299',
    messagingSenderId: '1034229118044',
    projectId: 'lunchsphere',
    storageBucket: 'lunchsphere.appspot.com',
    iosBundleId: 'com.example.lunchsphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJBzr_CM05sCOxZ4MswhKbL3NBmfVWuSU',
    appId: '1:1034229118044:ios:ada44ba2d6fdfb2dce2299',
    messagingSenderId: '1034229118044',
    projectId: 'lunchsphere',
    storageBucket: 'lunchsphere.appspot.com',
    iosBundleId: 'com.example.lunchsphere.RunnerTests',
  );
}
